version: "3.7"

services:
  mongo:
    platform: "linux/amd64"
    container_name: mongo
    restart: always
    image: mongo:4.4.7
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - appnet

  server:
    build: "../"
    container_name: docker_server
    restart: always
    environment:
      FABU_DB_HOST: mongo
      FABU_BASE_URL: http://3.27.146.254:9898/
      FABU_UPLOAD_DIR: /fabu/upload
    ports:
      - "9898:9898"
    volumes:
      - ./upload:/fabu/upload
    depends_on:
      - mongo
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
